- name: Check if jenkins job already exists
  community.general.jenkins_job_info:
    name: "{{ item.job_name }}"
    user: admin
    password: admin
    url: http://172.31.8.64:8080
  register: jenkins_job_status
  ignore_errors: true

- name: Copy Xml file
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/test.xml
  when: jenkins_job_status.failed or override


- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: "{{ item.job_name }}"
    password: admin
    url: http://172.31.8.64:8080
    user: admin
  when: jenkins_job_status.failed or override
