sjobs:
  - { git_repo_url: https://github.com/Naveen2015/roboshop-terraform-new.git, job_name: roboshop-terraform}
  - { git_repo_url: https://github.com/Naveen2015/roboshop-ansible-new.git, job_name: roboshop-ansible}